apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: REFRESH_JWT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: REFRESH_JWT_SECRET
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: DATABASE_URL
             - name: PASSWORD_RECOVERY_CODE_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: PASSWORD_RECOVERY_CODE_SECRET
             - name: EMAIL_CONFIRMATION_CODE_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: EMAIL_CONFIRMATION_CODE_SECRET
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: OAUTH_REDIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: OAUTH_REDIRECT_URL
             - name: DOMAIN
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: DOMAIN
             - name: GITHUB_OAUTH_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GITHUB_OAUTH_CALLBACK_URL
             - name: GOOGLE_OAUTH_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: GOOGLE_OAUTH_CALLBACK_URL
             - name: ACCESS_JWT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incstagram-back-production-config-secret
                   key: ACCESS_JWT_SECRET
